# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BigBigBoy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BigBigBoy
	pod 'Fabric'
	pod 'Crashlytics'
  target 'BigBigBoyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BigBigBoyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
